name: CI

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: mymindstorm/setup-emsdk@v12
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - run: npm ci
            - run: npm run lint:nofix
            - run: npm run build:wasm
            - run: npm run build
            - run: npm test
            - run: npm run luatests
            - uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
