name: Testing

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - uses: mymindstorm/setup-emsdk@v7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run lint
            - run: npm run build:wasm
            - run: npm run build
            - run: npm test
